name: CI/run
on: 
  workflow_dispatch:
 
jobs:
 check01:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Run Checking
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.CRIMAGE }}
            run: |
                KEY="${{ secrets.CRKEY1 }}" ./start.sh

 check02:
    runs-on: ubuntu-latest
    needs: check01
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Run Checking
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.CRIMAGE }}
            run: |
                KEY="${{ secrets.CRKEY2 }}" ./start.sh

 # check03:
 #    runs-on: ubuntu-latest
 #    needs: check02
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY3 }}" ./start.sh

 # check04:
 #    runs-on: ubuntu-latest
 #    needs: check03
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY4 }}" ./start.sh

 # check05:
 #    runs-on: ubuntu-latest
 #    needs: check04
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY5 }}" ./start.sh

 # check06:
 #    runs-on: ubuntu-latest
 #    needs: check05
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY6 }}" ./start.sh

 # check07:
 #    runs-on: ubuntu-latest
 #    needs: check06
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY7 }}" ./start.sh

 # check08:
 #    runs-on: ubuntu-latest
 #    needs: check07
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY8 }}" ./start.sh

 # check09:
 #    runs-on: ubuntu-latest
 #    needs: check08
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY9 }}" ./start.sh

 # check10:
 #    runs-on: ubuntu-latest
 #    needs: check09
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY10 }}" ./start.sh

 # check11:
 #    runs-on: ubuntu-latest
 #    needs: check10
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY11 }}" ./start.sh

 # check12:
 #    runs-on: ubuntu-latest
 #    needs: check11
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY12 }}" ./start.sh

 # check13:
 #    runs-on: ubuntu-latest
 #    needs: check12
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY13 }}" ./start.sh

 # check14:
 #    runs-on: ubuntu-latest
 #    needs: check13
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY14 }}" ./start.sh

 # check15:
 #    runs-on: ubuntu-latest
 #    needs: check14
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY15 }}" ./start.sh

 # check16:
 #    runs-on: ubuntu-latest
 #    needs: check15
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY16 }}" ./start.sh

 # check17:
 #    runs-on: ubuntu-latest
 #    needs: check16
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY17 }}" ./start.sh

 # check18:
 #    runs-on: ubuntu-latest
 #    needs: check17
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY18 }}" ./start.sh

 # check19:
 #    runs-on: ubuntu-latest
 #    needs: check18
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY19 }}" ./start.sh

 # check20:
 #    runs-on: ubuntu-latest
 #    needs: check19
 #    timeout-minutes: 360
 #    steps:
 #      - uses: actions/checkout@v2
 #        name: Checkout
 #      - name: Run Checking
 #        uses: addnab/docker-run-action@v3
 #        with:
 #            image: ${{ secrets.CRIMAGE }}
 #            run: |
 #                KEY="${{ secrets.CRKEY20 }}" ./start.sh
